Updating latest translations.
microapps-test/workspace-microapps-test pull request #65
Opened 2020-08-10 09:03 UTC by sivanatase1-ctxs

updating available translations,

2020-08-11 13:21 UTC, yiminl-ctx commented on bundles/http/Citrix/66cf6f1a-e71d-44df-88c5-3db3e99ef7da/i18n/de.json
> +    "7901d093-fca6-4e34-be78-e11fcfb02a2e": "No email address found",
Why this string is not translated?

2020-08-11 13:22 UTC, yiminl-ctx commented on bundles/http/Citrix/66cf6f1a-e71d-44df-88c5-3db3e99ef7da/i18n/de.json
> +    "c3d2100c-8145-4106-af7b-3a31f17fbd29": "No phone number found",
Why this string is not translated?

2020-08-11 13:22 UTC, yiminl-ctx commented on bundles/http/Citrix/66cf6f1a-e71d-44df-88c5-3db3e99ef7da/i18n/de.json
> +    "d3edd09d-375c-4093-adf5-b64ece35f3e8": "User is not part of any organization",
Why this string is not translated?

2020-08-11 14:24 UTC, yiminl-ctx commented on bundles/http/Citrix/f1c0fcac-0764-4a21-96b8-77a0316e337d/i18n/de.json
> +    "1382a579-1fd6-47cd-ac0b-7d89579b5c46": "Incident {{number}} - '{{short_description}}' has been assigned to {{assigned_to__incident.name}}.",
the {{assigned_to__incident.name}} has been modified,it should be {{assigned_to_incident.name}}

2020-08-11 14:30 UTC, ghost requested changes
Some mustache templates  have been modified, for example:
{{assigned_to__incident.name}} should be {{assigned_to_incident.name}}
{{state__incident.label}} should be {{state_incident.label}}

could you please check all the modified templates?

2020-08-11 15:16 UTC, ghost approved these changes

2020-08-11 15:22 UTC, yiminl-ctx commented
> Some mustache templates have been modified, for example:
> {{assigned_to__incident.name}} should be {{assigned_to_incident.name}}
> {{state__incident.label}} should be {{state_incident.label}}
> 
> could you please check all the modified templates?

Ignore this comment, translation is correct, because the content of the EN template has changed

2020-08-12 03:08 UTC, yangwa-ctx approved these changes

2020-08-27 07:41 UTC, closed without merging

2020-08-27 07:41 UTC, sivanatase1-ctxs commented
later changes are merged to the branch